# Generated by Django 4.2.1 on 2023-05-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysight_app', '0002_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50)),
                ('carrier_code', models.CharField(max_length=50)),
                ('tracking_info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
