# Generated by Django 4.2.1 on 2023-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skysight_app', '0003_package_delete_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=255)),
                ('departure_timezone', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('departure_terminal', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=255)),
                ('arrival_timezone', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('arrival_terminal', models.CharField(max_length=100)),
                ('airline_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
