# Generated by Django 4.2.1 on 2023-05-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skysight_app', '0005_weatherdata_delete_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
