# Generated by Django 4.2.1 on 2023-05-12 17:30

from django.db import migrations


from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('skysight_app', '0007_weatherdata_maxtemp_c_weatherdata_maxwind_kph_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE skysight_app_weatherdata SET user_id = 1 WHERE user_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
