# Generated by Django 4.2.1 on 2023-05-12 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skysight_app', '0009_alter_weatherdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='maxtemp_c',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='maxwind_kph',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='mintemp_c',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='totalprecip_mm',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='uv',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
